import { StyleSheet } from "react-native";
import Theme from "../../utils/Theme";
const styles = StyleSheet.create({
  mainView: {
    flex: 1,
  },
  View1: {
    height: Theme.hp("10%"),
    justifyContent: "center",
  },
  signuptxt: {
    color: Theme.black,
    textAlign: "center",
    fontSize: 25,
    fontWeight: "700",
  },
  signuptxt1: {
    color: Theme.black,
    textAlign: "center",
    fontSize: 25,
    fontWeight: "700",
    margin: 10,
  },
  textinputconatiner: {
    height: Theme.hp("70%"),
  },
  txtinput: {
    marginTop: 5,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#87CEEB",
    borderRadius: 1,
    // fontFamily: "regular",
    fontSize: 14,
    paddingLeft: 15,
    borderRadius: 5,
    paddingHorizontal: 10,
    // backgroundColor: "",
    height: Theme.hp("7%"),
    width: Theme.wp("90%"),
    alignSelf: "center",
  },
  txtinputAddress: {
    marginTop: 5,
    marginLeft: "5%",
    borderWidth: 1,
    color: "#87CEEB",
    borderColor: "#87CEEB",
    borderRadius: 1,
    fontSize: 14,
    borderRadius: 5,
    paddingHorizontal: 10,
    // backgroundColor: "#FAFAFA",
    height: Theme.hp("7%"),
    width: Theme.wp("65%"),
  },
  txtinputHouse: {
    marginTop: 5,
    marginLeft: "1%",
    borderWidth: 1,
    borderColor: "#87CEEB",
    borderRadius: 1,
    fontSize: 14,
    borderRadius: 5,
    paddingHorizontal: 10,
    // backgroundColor: "#FAFAFA",
    height: Theme.hp("7%"),
    width: Theme.wp("22%"),
  },
  txtinputCity: {
    marginTop: 5,
    marginLeft: "5%",
    borderWidth: 1,
    color: "#87CEEB",
    borderColor: "#87CEEB",
    borderRadius: 1,
    fontSize: 14,
    borderRadius: 5,
    paddingHorizontal: 10,
    // backgroundColor: "#FAFAFA",
    height: Theme.hp("7%"),
    width: Theme.wp("60%"),
  },
  txtinputPostalCode: {
    marginTop: 5,
    marginLeft: "1%",
    borderWidth: 1,
    borderColor: "#87CEEB",
    borderRadius: 1,
    fontSize: 14,
    borderRadius: 5,
    paddingHorizontal: 10,
    // backgroundColor: "#FAFAFA",
    height: Theme.hp("7%"),
    width: Theme.wp("27%"),
  },
  yes: {
    margin: 10,

    height: Theme.hp("4%"),
    width: Theme.wp("40%"),
    backgroundColor: "blue",
    borderRadius: 5,
    marginLeft: "5%",
    opacity: 0.8,
  },
  no: {
    margin: 10,
    height: Theme.hp("4%"),
    width: Theme.wp("40%"),
    backgroundColor: "blue",
    borderRadius: 5,
    marginRight: "5%",
    opacity: 0.8,
  },
});
export default styles;
